//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Commands.StorSimple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Commands.StorSimple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} job failed to submit. .
        /// </summary>
        internal static string FailureMessageSubmitJob {
            get {
                return ResourceManager.GetString("FailureMessageSubmitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the EncryptionKey..
        /// </summary>
        internal static string NotAllowedErrorDataContainerEncryption {
            get {
                return ResourceManager.GetString("NotAllowedErrorDataContainerEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified access control record does not exist..
        /// </summary>
        internal static string NotFoundMessageACR {
            get {
                return ResourceManager.GetString("NotFoundMessageACR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified device does not exist..
        /// </summary>
        internal static string NotFoundMessageDevice {
            get {
                return ResourceManager.GetString("NotFoundMessageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified resource does not exist..
        /// </summary>
        internal static string NotFoundMessageResource {
            get {
                return ResourceManager.GetString("NotFoundMessageResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified storage account does not exist..
        /// </summary>
        internal static string NotFoundMessageStorageAccount {
            get {
                return ResourceManager.GetString("NotFoundMessageStorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified volume does not exist..
        /// </summary>
        internal static string NotFoundMessageVirtualDisk {
            get {
                return ResourceManager.GetString("NotFoundMessageVirtualDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing backup with backupId {0}....
        /// </summary>
        internal static string RemoveASSDBackupMessage {
            get {
                return ResourceManager.GetString("RemoveASSDBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing backuppolicy with backuppolicyId {0}....
        /// </summary>
        internal static string RemoveASSDBackupPolicyMessage {
            get {
                return ResourceManager.GetString("RemoveASSDBackupPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the backuppolicy with backuppolicyId{0}?.
        /// </summary>
        internal static string RemoveASSDBackupPolicyWarningMessage {
            get {
                return ResourceManager.GetString("RemoveASSDBackupPolicyWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the backup with backupId{0}?.
        /// </summary>
        internal static string RemoveASSDBackupWarningMessage {
            get {
                return ResourceManager.GetString("RemoveASSDBackupWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing access control record....
        /// </summary>
        internal static string RemoveConfirmationACR {
            get {
                return ResourceManager.GetString("RemoveConfirmationACR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing volume container....
        /// </summary>
        internal static string RemoveConfirmationDataContainer {
            get {
                return ResourceManager.GetString("RemoveConfirmationDataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing storage account....
        /// </summary>
        internal static string RemoveConfirmationSAC {
            get {
                return ResourceManager.GetString("RemoveConfirmationSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing volume....
        /// </summary>
        internal static string RemoveConfirmationVolume {
            get {
                return ResourceManager.GetString("RemoveConfirmationVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the access control record?.
        /// </summary>
        internal static string RemoveWarningACR {
            get {
                return ResourceManager.GetString("RemoveWarningACR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the volume container?.
        /// </summary>
        internal static string RemoveWarningDataContainer {
            get {
                return ResourceManager.GetString("RemoveWarningDataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the storage account?.
        /// </summary>
        internal static string RemoveWarningSAC {
            get {
                return ResourceManager.GetString("RemoveWarningSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the volume?.
        /// </summary>
        internal static string RemoveWarningVolume {
            get {
                return ResourceManager.GetString("RemoveWarningVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup with backupId {0}....
        /// </summary>
        internal static string StartASSDBackupRestoreJobMessage {
            get {
                return ResourceManager.GetString("StartASSDBackupRestoreJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the backup with backupId{0}?.
        /// </summary>
        internal static string StartASSDBackupRestoreJobWarningMessage {
            get {
                return ResourceManager.GetString("StartASSDBackupRestoreJobWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context set successfully for the given resource name..
        /// </summary>
        internal static string SuccessMessageSetResourceContext {
            get {
                return ResourceManager.GetString("SuccessMessageSetResourceContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} job is submitted successfully. Please use the command Get-AzureStorSimpleJob -InstanceId {1} for tracking the job status.
        /// </summary>
        internal static string SuccessMessageSubmitJob {
            get {
                return ResourceManager.GetString("SuccessMessageSubmitJob", resourceCulture);
            }
        }
    }
}
